---

name: Run RSpec

on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - 'rails/**/*'

env:
  RAILS_ENV: test

jobs:
  build-rails:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - name: Restore from and save to external cache
        uses: actions/cache@v4
        with:
          path: .cache/${{ github.repository }}/docker-build-cache
          key: ${{ runner.os }}-lo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-lo-

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./rails
          push: true
          tags: dockerdxm/nx01-rails:test
          cache-from: |
            type=local,src=.cache/${{ github.repository }}/docker-build-cache
          cache-to: |
            type=local,dest=.cache/${{ github.repository }}/docker-build-cache
          build-args: |
            RAILS_ENV=test

  rspec:
    needs: build-rails

    runs-on: ubuntu-latest

    container:
      image: dockerdxm/nx01-rails:test
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      env:
        MYSQL_DB_HOST: mysql
        MYSQL_DB_PORT: 3306
        MYSQL_DATABASE: nx01
        MYSQL_USER: app_user
        MYSQL_PASSWORD: password
        MYSQL_TEST_DB_HOST: mysql
        RAILS_ENV: test

    services:
      mysql:
        image: mysql:8.3.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: nx01
          MYSQL_USER: app_user
          MYSQL_PASSWORD: password
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping -h localhost --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    defaults:
      run:
        working-directory: ./rails

    steps:
      - uses: actions/checkout@v4

      - name: Setup database
        run: bundle exec rails db:migrate

      - name: Run RSpec
        run: bundle exec rspec -fd --force-color
